Repository devs-plan/Ketchup_Back-end, pull requests merged in 2024-05, with the labels that each got.

#93 [Feature-0501] - 퇴사처리 구현
  http/memberRestAPI.http
  http/noticeRestAPI.http
  src/main/java/com/devsplan/ketchup/auth/config/WebSecurityConfig.java
  src/main/java/com/devsplan/ketchup/auth/filter/JwtAuthorizationFilter.java
  src/main/java/com/devsplan/ketchup/auth/handler/CustomAuthenticationProvider.java
  src/main/java/com/devsplan/ketchup/board/dto/BoardDTO.java
  src/main/java/com/devsplan/ketchup/common/Authority.java
  src/main/java/com/devsplan/ketchup/common/utils/TokenUtils.java
  src/main/java/com/devsplan/ketchup/config/WebConfig.java
  src/main/java/com/devsplan/ketchup/member/controller/AuthController.java
  src/main/java/com/devsplan/ketchup/member/dto/DepDTO.java
  src/main/java/com/devsplan/ketchup/member/dto/MemberDTO.java
  src/main/java/com/devsplan/ketchup/member/dto/PositionDTO.java
  src/main/java/com/devsplan/ketchup/member/entity/Dep.java
  src/main/java/com/devsplan/ketchup/member/entity/Member.java
  src/main/java/com/devsplan/ketchup/member/entity/Position.java
  src/main/java/com/devsplan/ketchup/member/repository/MemberRepository.java
  src/main/java/com/devsplan/ketchup/member/service/MemberService.java
  src/main/resources/application.yml
  src/test/java/com/devsplan/ketchup/member/MemberRestTest.java
Labels: 기능구현

#94 [Feature-0501]() - 메일 - 메일 컨트롤러 추가 및 서비스 수정
  http/mailRestAPI.http
  src/main/java/com/devsplan/ketchup/mail/controller/MailController.java
  src/main/java/com/devsplan/ketchup/mail/dto/MailFileDTO.java
  src/main/java/com/devsplan/ketchup/mail/dto/ReceiverDTO.java
  src/main/java/com/devsplan/ketchup/mail/entity/Mail.java
  src/main/java/com/devsplan/ketchup/mail/entity/Receiver.java
  src/main/java/com/devsplan/ketchup/mail/repository/MailRepository.java
  src/main/java/com/devsplan/ketchup/mail/repository/ReceiverRepository.java
  src/main/java/com/devsplan/ketchup/mail/service/MailService.java
  src/main/java/com/devsplan/ketchup/rsc/entity/Rsc.java
  src/test/java/com/devsplan/ketchup/mail/controller/MailControllerTests.java
  src/test/java/com/devsplan/ketchup/mail/service/MailRestTests.java
Labels: 디벨롭, 기능구현

#96 [Feature-0501] - 사원등록시 파일업로드 추가
  http/memberRestAPI.http
  http/pikachu.png
  src/main/java/com/devsplan/ketchup/member/controller/MemberController.java
  src/main/java/com/devsplan/ketchup/member/controller/TestController.java
  src/main/java/com/devsplan/ketchup/member/service/MemberService.java
  src/main/resources/static/uploadfiles/b33a0279fd174481862679eee7216e2f.png
  src/test/java/com/devsplan/ketchup/member/MemberRestTest.java
Labels: 기능구현

#98 [Feature-0502](#97 #83) - 전자결재상신, 양식 조회
  http/approvalRestAPI.http
  src/main/java/com/devsplan/ketchup/approval/controller/ApprovalController.java
  src/main/java/com/devsplan/ketchup/approval/dto/AppInputDTO.java
  src/main/java/com/devsplan/ketchup/approval/dto/AppUpdateDTO.java
  src/main/java/com/devsplan/ketchup/approval/dto/ApprovalDTO.java
  src/main/java/com/devsplan/ketchup/approval/dto/ApprovalSelectDTO.java
  src/main/java/com/devsplan/ketchup/approval/entity/AppMember.java
  src/main/java/com/devsplan/ketchup/approval/entity/Approval.java
  src/main/java/com/devsplan/ketchup/approval/entity/ApprovalSelect.java
  src/main/java/com/devsplan/ketchup/approval/repository/AppLineRepository.java
  src/main/java/com/devsplan/ketchup/approval/repository/ApprovalSelectRepository.java
  src/main/java/com/devsplan/ketchup/approval/repository/FormRepository.java
  src/main/java/com/devsplan/ketchup/approval/repository/RefLineRepository.java
  src/main/java/com/devsplan/ketchup/approval/service/ApprovalService.java
  src/test/java/com/devsplan/ketchup/approval/ApprovalControllerTests.java
  src/test/java/com/devsplan/ketchup/approval/ApprovalRestTests.java
Labels: 기능구현

#100 [Feature-0502] - 엔티티 빌드패턴 적용, 토큰 클레임생성 수정
  http/memberRestAPI.http
  src/main/java/com/devsplan/ketchup/auth/filter/JwtAuthorizationFilter.java
  src/main/java/com/devsplan/ketchup/auth/handler/CustomAuthSuccessHandler.java
  src/main/java/com/devsplan/ketchup/auth/model/DetailsMember.java
  src/main/java/com/devsplan/ketchup/auth/model/service/DetailsService.java
  src/main/java/com/devsplan/ketchup/member/dto/PositionDTO.java
  src/main/java/com/devsplan/ketchup/member/entity/Dep.java
  src/main/java/com/devsplan/ketchup/member/entity/Member.java
  src/main/java/com/devsplan/ketchup/member/entity/Position.java
  src/main/java/com/devsplan/ketchup/member/repository/MemberRepository.java
  src/main/java/com/devsplan/ketchup/member/service/MemberService.java
  src/main/java/com/devsplan/ketchup/util/TokenUtils.java
  src/main/resources/static/uploadfiles/0058206e0bb64a03983cdaedc99301b6.png
  src/main/resources/static/uploadfiles/18ec97b13fd34f9189f4a59edea213e0.png
  src/main/resources/static/uploadfiles/1c940e78d3dc4804a245becb56ddd615.png
  src/main/resources/static/uploadfiles/278d77d9b77542b3b1a663624018ec7c.png
  src/main/resources/static/uploadfiles/2a613ae59bf14a8e8845f86da777f2c4.png
  src/main/resources/static/uploadfiles/7b9eda3410134728a18bdccdd4eb9637.png
  src/main/resources/static/uploadfiles/7d17059684fc4f23a5ff31fe6078af35.png
  src/main/resources/static/uploadfiles/7d221baa1973452d9dd7efba878fd89b.png
  src/main/resources/static/uploadfiles/c58231044cf44e5d891936f5b4613d5c.png
  src/main/resources/static/uploadfiles/d4b386df04e14e99912743144668e769.png
  src/main/resources/static/uploadfiles/f49043dd587b4e51be2b635ed29fe692.png
Labels: 디벨롭

#102 [Feature-0502](#101) - 메일 - 메일 답장
  http/mailRestAPI.http
  src/main/java/com/devsplan/ketchup/mail/controller/MailController.java
  src/main/java/com/devsplan/ketchup/mail/dto/MailDTO.java
  src/main/java/com/devsplan/ketchup/mail/dto/ReceiverDTO.java
  src/main/java/com/devsplan/ketchup/mail/entity/Mail.java
  src/main/java/com/devsplan/ketchup/mail/entity/Receiver.java
  src/main/java/com/devsplan/ketchup/mail/service/MailService.java
  src/test/java/com/devsplan/ketchup/mail/controller/MailControllerTests.java
  src/test/java/com/devsplan/ketchup/mail/service/MailRestTests.java
Labels: 기능구현

#104 [Feature-0502] - 복호화 메소드 추가
  http/memberRestAPI.http
  src/main/java/com/devsplan/ketchup/common/PageDTO.java
  src/main/java/com/devsplan/ketchup/common/Pagenation.java
  src/main/java/com/devsplan/ketchup/common/PagingButton.java
  src/main/java/com/devsplan/ketchup/member/controller/MemberController.java
  src/main/java/com/devsplan/ketchup/member/controller/TestController.java
  src/main/java/com/devsplan/ketchup/member/repository/MemberRepository.java
  src/main/java/com/devsplan/ketchup/member/service/MemberService.java
  src/main/java/com/devsplan/ketchup/util/TokenUtils.java
  src/main/resources/static/uploadfiles/0058206e0bb64a03983cdaedc99301b6.png
  src/main/resources/static/uploadfiles/18ec97b13fd34f9189f4a59edea213e0.png
  src/main/resources/static/uploadfiles/1c940e78d3dc4804a245becb56ddd615.png
  src/main/resources/static/uploadfiles/278d77d9b77542b3b1a663624018ec7c.png
  src/main/resources/static/uploadfiles/2a613ae59bf14a8e8845f86da777f2c4.png
  src/main/resources/static/uploadfiles/7b9eda3410134728a18bdccdd4eb9637.png
  src/main/resources/static/uploadfiles/7d17059684fc4f23a5ff31fe6078af35.png
  src/main/resources/static/uploadfiles/7d221baa1973452d9dd7efba878fd89b.png
  src/main/resources/static/uploadfiles/b33a0279fd174481862679eee7216e2f.png
  src/main/resources/static/uploadfiles/c58231044cf44e5d891936f5b4613d5c.png
  src/main/resources/static/uploadfiles/d4b386df04e14e99912743144668e769.png
  src/main/resources/static/uploadfiles/f49043dd587b4e51be2b635ed29fe692.png
  src/test/java/com/devsplan/ketchup/member/MemberTest.java
Labels: 디벨롭

#108 [Feature-0502](#107 ) - ReserveService - 자원 예약 목록 조회 테스트 코드 업데이트
  src/main/java/com/devsplan/ketchup/reserve/repository/ReserveRepository.java
  src/main/java/com/devsplan/ketchup/reserve/repository/ResourceRepository.java
  src/main/java/com/devsplan/ketchup/reserve/service/ReserveService.java
  src/test/java/com/devsplan/ketchup/reserve/ReserveServiceTests.java
Labels: 디벨롭

#111 [Feature-0502](#110) - reserve - 자원 예약 상세 조회 테스트 코드 작성 완료
  .DS_Store
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/.DS_Store
  src/main/java/com/.DS_Store
  src/main/java/com/devsplan/.DS_Store
  src/main/java/com/devsplan/ketchup/.DS_Store
  src/main/java/com/devsplan/ketchup/common/Pagenation.java
  src/main/java/com/devsplan/ketchup/common/PagingButton.java
  src/main/java/com/devsplan/ketchup/reserve/service/ReserveService.java
  src/test/java/com/devsplan/ketchup/reserve/ReserveServiceTests.java
Labels: 기능구현

#113 240502 hoo 3
  http/memberRestAPI.http
  src/main/java/com/devsplan/ketchup/member/controller/MemberController.java
  src/main/java/com/devsplan/ketchup/member/controller/TestController.java
  src/main/java/com/devsplan/ketchup/member/repository/MemberRepository.java
  src/main/java/com/devsplan/ketchup/member/service/MemberService.java
Labels: 기능구현

#117 [Feature-0503](#115) - notice - 공지 파일업로드, 다운로드, 페이징 처리 controller, service 수정
  http/noticeRestAPI.http
  src/main/java/com/devsplan/ketchup/board/service/BoardService.java
  src/main/java/com/devsplan/ketchup/notice/controller/NoticeController.java
  src/main/java/com/devsplan/ketchup/notice/dto/NoticeDTO.java
  src/main/java/com/devsplan/ketchup/notice/dto/NoticeFileDTO.java
  src/main/java/com/devsplan/ketchup/notice/entity/Notice.java
  src/main/java/com/devsplan/ketchup/notice/entity/NoticeFile.java
  src/main/java/com/devsplan/ketchup/notice/service/NoticeService.java
Labels: 디벨롭, 기능구현

#120 [Feature-0503](#118 #119) - 기안목록 조회, controller test
  src/main/java/com/devsplan/ketchup/approval/controller/ApprovalController.java
  src/main/java/com/devsplan/ketchup/approval/dto/AppInputDTO.java
  src/main/java/com/devsplan/ketchup/approval/dto/AppLineAndMemberDTO.java
  src/main/java/com/devsplan/ketchup/approval/dto/AppUpdateDTO.java
  src/main/java/com/devsplan/ketchup/approval/dto/ApprovalSelectDTO.java
  src/main/java/com/devsplan/ketchup/approval/dto/MemberDTO.java
  src/main/java/com/devsplan/ketchup/approval/dto/RefLineAndMemberDTO.java
  src/main/java/com/devsplan/ketchup/approval/entity/AppLine.java
  src/main/java/com/devsplan/ketchup/approval/entity/AppLineAndMember.java
  src/main/java/com/devsplan/ketchup/approval/entity/AppMember.java
  src/main/java/com/devsplan/ketchup/approval/entity/ApprovalSelect.java
  src/main/java/com/devsplan/ketchup/approval/entity/Member.java
  src/main/java/com/devsplan/ketchup/approval/entity/RefLineAndMember.java
  src/main/java/com/devsplan/ketchup/approval/repository/ApprovalSelectRepository.java
  src/main/java/com/devsplan/ketchup/approval/service/ApprovalService.java
  src/test/java/com/devsplan/ketchup/approval/ApprovalControllerTests.java
  src/test/java/com/devsplan/ketchup/approval/ApprovalServiceTests.java
Labels: 디벨롭, 기능구현

#121 [Feature-0503] - board, notice - 부서별 자료실, 공지 service test 코드 수정
  src/test/java/com/devsplan/ketchup/board/service/BoardServiceTests.java
  src/test/java/com/devsplan/ketchup/notice/service/NoticeServiceTests.java
Labels: 디벨롭

#123 [Feature-0503] - {MemberController, MemberTest,Member} 사원 상세조회 추가
  http/memberRestAPI.http
  src/main/java/com/devsplan/ketchup/member/controller/MemberController.java
  src/test/java/com/devsplan/ketchup/member/MemberTest.java
Labels: 기능구현

#124 [Feature-0503](#109) - reserve - 예약 수정 서비스 테스트 코드 작성
  src/main/java/com/devsplan/ketchup/common/.DS_Store
  src/main/java/com/devsplan/ketchup/reserve/dto/ReserveDTO.java
  src/main/java/com/devsplan/ketchup/reserve/entity/Reserve.java
  src/main/java/com/devsplan/ketchup/reserve/service/ReserveService.java
  src/test/java/com/devsplan/ketchup/board/service/BoardServiceTests.java
  src/test/java/com/devsplan/ketchup/notice/service/NoticeServiceTests.java
  src/test/java/com/devsplan/ketchup/reserve/ReserveServiceTests.java
  src/test/java/com/devsplan/ketchup/schedule/ScheduleServiceTests.java
Labels: 기능구현

#126 [Feature-0503](# #) - 메일 - 메일 검색 조회(제목) 및 보낸 메일 조회 수정
  http/mailRestAPI.http
  src/main/java/com/devsplan/ketchup/mail/controller/MailController.java
  src/main/java/com/devsplan/ketchup/mail/dto/MailFileDTO.java
  src/main/java/com/devsplan/ketchup/mail/dto/ReceiverDTO.java
  src/main/java/com/devsplan/ketchup/mail/entity/MailFile.java
  src/main/java/com/devsplan/ketchup/mail/repository/MailFileRepository.java
  src/main/java/com/devsplan/ketchup/mail/repository/MailRepository.java
  src/main/java/com/devsplan/ketchup/mail/service/MailService.java
  src/main/java/com/devsplan/ketchup/rsc/dto/RscDTO.java
  src/main/java/com/devsplan/ketchup/rsc/entity/Rsc.java
  src/main/java/com/devsplan/ketchup/rsc/repository/RscRepository.java
  src/main/java/com/devsplan/ketchup/rsc/service/RscService.java
  src/test/java/com/devsplan/ketchup/mail/service/MailServiceTests.java
  src/test/java/com/devsplan/ketchup/rsc/RscServiceTests.java
Labels: 디벨롭

#127 [Feature-0503](# ) - approval rest api 테스트 - http 파일 추가
  http/approvalRestAPI.http
  src/main/java/com/devsplan/ketchup/approval/controller/ApprovalController.java
  src/main/java/com/devsplan/ketchup/approval/service/ApprovalService.java
  src/test/java/com/devsplan/ketchup/approval/ApprovalServiceTests.java
Labels: 디벨롭

#129 [Feature-0503](#125) - reserve - 예약 삭제 서비스 테스트 코드 작성
  src/main/java/com/devsplan/ketchup/reserve/service/ReserveService.java
  src/test/java/com/devsplan/ketchup/reserve/ReserveServiceTests.java
Labels: 기능구현

#130 [Feature-0503] - 전체 사원 조회시 이름으로 검색 추가
  http/memberRestAPI.http
  src/main/java/com/devsplan/ketchup/member/controller/MemberController.java
  src/main/java/com/devsplan/ketchup/member/repository/MemberRepository.java
  src/main/java/com/devsplan/ketchup/member/service/MemberService.java
Labels: 기능구현

#131 [Feature-0503](#31 #85) - 메일 - 메일 파일 업로드
  http/mailRestAPI.http
  src/main/java/com/devsplan/ketchup/mail/controller/MailController.java
  src/main/java/com/devsplan/ketchup/mail/service/MailService.java
  src/main/java/com/devsplan/ketchup/rsc/dto/RscDTO.java
  src/test/java/com/devsplan/ketchup/rsc/RscServiceTests.java
Labels: 디벨롭

#136 [Feature-0503] - 입력한 사원의 개인메일로 인증번호 발송
  build.gradle
  http/memberRestAPI.http
  src/main/java/com/devsplan/ketchup/member/controller/MemberController.java
  src/main/java/com/devsplan/ketchup/member/repository/MemberRepository.java
  src/main/java/com/devsplan/ketchup/member/service/MemberService.java
  src/main/resources/application.yml
Labels: 기능구현

#139 [Feature-0503](#138) - reserve - ReserveControllerTests 파일 생성, 예약 목록 조회, 예약 등록 컨트롤러 테스트 코드 성공
  http/reserveRestAPI.http
  http/scheduleRestAPI.http
  src/main/java/com/devsplan/ketchup/reserve/controller/ReserveController.java
  src/main/java/com/devsplan/ketchup/reserve/controller/ResponseMessage.java
  src/main/java/com/devsplan/ketchup/reserve/dto/ReserveDTO.java
  src/main/java/com/devsplan/ketchup/reserve/service/ReserveService.java
  src/main/java/com/devsplan/ketchup/schedule/controller/ScheduleController.java
  src/test/java/com/devsplan/ketchup/reserve/ReserveControllerTests.java
  src/test/java/com/devsplan/ketchup/reserve/ReserveServiceTests.java
Labels: 기능구현

#142 [Feature-0506](#141) - 자원 관리 - 자원 수정, 삭제 테스트
  src/main/java/com/devsplan/ketchup/rsc/dto/RscDTO.java
  src/main/java/com/devsplan/ketchup/rsc/entity/Rsc.java
  src/main/java/com/devsplan/ketchup/rsc/repository/RscRepository.java
  src/main/java/com/devsplan/ketchup/rsc/service/RscService.java
  src/test/java/com/devsplan/ketchup/rsc/RscServiceTests.java
Labels: 기능구현

#143 [Feature-0506] - 메일 - 메일 엔티티 setter 사용 수정
  src/main/java/com/devsplan/ketchup/mail/dto/MailDTO.java
  src/main/java/com/devsplan/ketchup/mail/dto/ReceiverDTO.java
  src/main/java/com/devsplan/ketchup/mail/entity/Mail.java
  src/main/java/com/devsplan/ketchup/mail/entity/MailFile.java
  src/main/java/com/devsplan/ketchup/mail/entity/Receiver.java
  src/main/java/com/devsplan/ketchup/mail/service/MailService.java
  src/main/java/com/devsplan/ketchup/rsc/entity/Rsc.java
  src/test/java/com/devsplan/ketchup/mail/service/MailServiceTests.java
Labels: 디벨롭

#145 [Feature-0507](#144) - 자원 - 자원 관리 controller 테스트 및 작성
  http/mailRestAPI.http
  http/rscRestAPI.http
  src/main/java/com/devsplan/ketchup/mail/repository/MailRepository.java
  src/main/java/com/devsplan/ketchup/mail/service/MailService.java
  src/main/java/com/devsplan/ketchup/rsc/controller/RscController.java
  src/main/java/com/devsplan/ketchup/rsc/dto/RscDTO.java
  src/main/java/com/devsplan/ketchup/rsc/entity/Rsc.java
  src/main/java/com/devsplan/ketchup/rsc/service/RscService.java
  src/test/java/com/devsplan/ketchup/mail/MailControllerTests.java
  src/test/java/com/devsplan/ketchup/mail/MailServiceTests.java
  src/test/java/com/devsplan/ketchup/rsc/RscControllerTests.java
  src/test/java/com/devsplan/ketchup/rsc/RscServiceTests.java
Labels: 기능구현

#146 [Feature-0508](#140) - reserve - 자원 예약 상세 조회, 수정, 삭제 컨트롤러 작성 및 테스트 코드 실행
  http/reserveRestAPI.http
  http/scheduleRestAPI.http
  src/main/java/com/devsplan/ketchup/reserve/controller/ReserveController.java
  src/main/java/com/devsplan/ketchup/reserve/entity/Reserve.java
  src/test/java/com/devsplan/ketchup/reserve/ReserveControllerTests.java
  src/test/java/com/devsplan/ketchup/schedule/ScheduleServiceTests.java
Labels: 기능구현

#148 [Feature-0504] - TokenUtils 수정
  http/memberRestAPI.http
  http/noticeRestAPI.http
  src/main/java/com/devsplan/ketchup/auth/filter/JwtAuthorizationFilter.java
  src/main/java/com/devsplan/ketchup/auth/handler/CustomAuthSuccessHandler.java
  src/main/java/com/devsplan/ketchup/config/WebConfig.java
  src/main/java/com/devsplan/ketchup/util/TokenUtils.java
Labels: 디벨롭

#150 [Feature-0508](#149) - reserve - 예약을 등록한 사용자만이 예약을 수정, 삭제 가능하도록 디벨롭
  src/main/java/com/devsplan/ketchup/reserve/controller/ReserveController.java
  src/main/java/com/devsplan/ketchup/reserve/dto/ReserveDTO.java
  src/main/java/com/devsplan/ketchup/reserve/entity/Reserve.java
  src/main/java/com/devsplan/ketchup/reserve/service/ReserveService.java
  src/test/java/com/devsplan/ketchup/reserve/ReserveControllerTests.java
  src/test/java/com/devsplan/ketchup/reserve/ReserveServiceTests.java
Labels: 디벨롭

#153 [Feature-0508] - {CustomAuthSuccessHandler} 내용 수정
  src/main/java/com/devsplan/ketchup/auth/handler/CustomAuthSuccessHandler.java
Labels: 디벨롭

#154 [Feature-0508] - 메일 - 메일 컨트롤러 수정
  src/main/java/com/devsplan/ketchup/mail/controller/MailController.java
  src/main/java/com/devsplan/ketchup/mail/repository/MailRepository.java
  src/main/java/com/devsplan/ketchup/mail/service/MailService.java
Labels: 디벨롭

#155 [Feature-0508] 자원 관리 - 자원 엔티티, dto 폴더 이동
  src/main/java/com/devsplan/ketchup/reserve/controller/ReserveController.java
  src/main/java/com/devsplan/ketchup/reserve/dto/ReserveDTO.java
  src/main/java/com/devsplan/ketchup/reserve/dto/ResourceDTO.java
  src/main/java/com/devsplan/ketchup/reserve/entity/Reserve.java
  src/main/java/com/devsplan/ketchup/reserve/entity/Resource.java
  src/main/java/com/devsplan/ketchup/reserve/repository/ReserveRepository.java
  src/main/java/com/devsplan/ketchup/reserve/repository/ResourceRepository.java
  src/main/java/com/devsplan/ketchup/reserve/service/ReserveService.java
  src/main/java/com/devsplan/ketchup/rsc/controller/RscController.java
  src/main/java/com/devsplan/ketchup/rsc/dto/ResourceDTO.java
  src/main/java/com/devsplan/ketchup/rsc/entity/Resource.java
  src/main/java/com/devsplan/ketchup/rsc/repository/RscRepository.java
  src/main/java/com/devsplan/ketchup/rsc/service/RscService.java
  src/test/java/com/devsplan/ketchup/mail/controller/MailControllerTests.java
  src/test/java/com/devsplan/ketchup/reserve/ReserveServiceTests.java
  src/test/java/com/devsplan/ketchup/rsc/RscServiceTests.java
Labels: 디벨롭

#156 [Feature-0508] 자원 - 자원 엔티티 수정
  src/main/java/com/devsplan/ketchup/reserve/entity/Reserve.java
Labels: 디벨롭

#157 [Feature-0509](#141) - 자원 관리 - 자원 수정 삭제 시 예약 삭제, 메일 전송
  src/main/java/com/devsplan/ketchup/reserve/repository/ReserveRepository.java
  src/main/java/com/devsplan/ketchup/rsc/controller/RscController.java
  src/main/java/com/devsplan/ketchup/rsc/service/RscService.java
Labels: 기능구현

#160 [Feature-0509] - {TokenUtils} 토큰 클레임 부서명 추가
  src/main/java/com/devsplan/ketchup/auth/filter/JwtAuthorizationFilter.java
  src/main/java/com/devsplan/ketchup/util/TokenUtils.java
Labels: 디벨롭

#163 [Feature-0509](#162) - ScheduleDTO - ScheduleDTO, Entity 수정
  http/memberRestAPI.http
  http/reserveRestAPI.http
  http/scheduleRestAPI.http
  src/main/java/com/devsplan/ketchup/common/ScheduleBuilder.java
  src/main/java/com/devsplan/ketchup/schedule/controller/ScheduleController.java
  src/main/java/com/devsplan/ketchup/schedule/dto/ScheduleDTO.java
  src/main/java/com/devsplan/ketchup/schedule/entity/Schedule.java
  src/main/java/com/devsplan/ketchup/schedule/service/ScheduleService.java
  src/test/java/com/devsplan/ketchup/reserve/ReserveServiceTests.java
  src/test/java/com/devsplan/ketchup/schedule/ScheduleServiceTests.java
Labels: 에러

#165 [Feature-0509] - {application.yml} 파일저장경로 수정
  src/main/java/com/devsplan/ketchup/member/service/MemberService.java
  src/main/java/com/devsplan/ketchup/util/TokenUtils.java
  src/main/resources/application.yml
Labels: 디벨롭

#167 [Feature-0510] - {MemberService} 전체사원 조회 수정 #166
  http/memberRestAPI.http
  src/main/java/com/devsplan/ketchup/auth/filter/JwtAuthorizationFilter.java
  src/main/java/com/devsplan/ketchup/member/service/MemberService.java
  src/main/resources/application.yml
Labels: 디벨롭

#168 [Feature-0510](issue 번호) - ScheduleController - 일정 컨트롤러 수정
  http/scheduleRestAPI.http
  src/main/java/com/devsplan/ketchup/schedule/controller/ScheduleController.java
  src/main/java/com/devsplan/ketchup/schedule/dto/ScheduleDTO.java
  src/main/java/com/devsplan/ketchup/schedule/repository/ScheduleRepository.java
  src/main/java/com/devsplan/ketchup/schedule/service/ScheduleService.java
  src/test/java/com/devsplan/ketchup/schedule/ScheduleServiceTests.java
Labels: 디벨롭, 에러

#170 [Feature-0510](#58) - noticeController - 공지 등록 controller, service 메소드 수정
  http/noticeRestAPI.http
  http/reserveRestAPI.http
  src/main/java/com/devsplan/ketchup/common/ResponseDTO.java
  src/main/java/com/devsplan/ketchup/mail/controller/MailController.java
  src/main/java/com/devsplan/ketchup/notice/controller/NoticeController.java
  src/main/java/com/devsplan/ketchup/notice/dto/NoticeDTO.java
  src/main/java/com/devsplan/ketchup/notice/service/NoticeService.java
Labels: 디벨롭

#171 [Feature-0511](#80) - notice - 공지 목록조회 service메소드 수정
  src/main/java/com/devsplan/ketchup/notice/controller/NoticeController.java
  src/main/java/com/devsplan/ketchup/notice/entity/Notice.java
  src/main/java/com/devsplan/ketchup/notice/repository/NoticeRepository.java
  src/main/java/com/devsplan/ketchup/notice/service/NoticeService.java
Labels: 디벨롭

#172 부서별 일정 수정 컨트롤, 서비스 부분 수정
  http/memberRestAPI.http
  http/scheduleRestAPI.http
  src/main/java/com/devsplan/ketchup/schedule/controller/ScheduleController.java
  src/main/java/com/devsplan/ketchup/schedule/service/ScheduleService.java
  src/test/java/com/devsplan/ketchup/schedule/ScheduleServiceTests.java
Labels: 디벨롭, 에러

#174 [Feature-0512](#58 #59) - notice - 공지 수정, 삭제 메소드 수정
  src/main/java/com/devsplan/ketchup/notice/controller/NoticeController.java
  src/main/java/com/devsplan/ketchup/notice/service/NoticeService.java
Labels: 디벨롭

#176 [Feature-0513](#175) - reserve - 자원 예약 컨트롤러 수정
  http/reserveRestAPI.http
  src/main/java/com/devsplan/ketchup/reserve/controller/ReserveController.java
  src/main/java/com/devsplan/ketchup/reserve/repository/ReserveRepository.java
  src/main/java/com/devsplan/ketchup/reserve/service/ReserveService.java
  src/test/java/com/devsplan/ketchup/reserve/ReserveControllerTests.java
  src/test/java/com/devsplan/ketchup/reserve/ReserveServiceTests.java
Labels: 디벨롭

#177 [Feature-0514](#19) - ApprovalService - 파일 업로드
  http/approvalRestAPI.http
  http/memberRestAPI.http
  src/main/java/com/devsplan/ketchup/approval/controller/ApprovalController.java
  src/main/java/com/devsplan/ketchup/approval/service/ApprovalService.java
  src/main/resources/application.yml
  src/test/java/com/devsplan/ketchup/approval/ApprovalControllerTests.java
Labels: 디벨롭

#178 [Feature-0514](#57 #58 #116) - notice - 공지 파일 업로드, 다운로드 entity, dto, service 수정
  http/noticeRestAPI.http
  src/main/java/com/devsplan/ketchup/notice/controller/NoticeController.java
  src/main/java/com/devsplan/ketchup/notice/dto/NoticeDTO.java
  src/main/java/com/devsplan/ketchup/notice/dto/NoticeFileDTO.java
  src/main/java/com/devsplan/ketchup/notice/entity/Notice.java
  src/main/java/com/devsplan/ketchup/notice/entity/NoticeFile.java
  src/main/java/com/devsplan/ketchup/notice/service/NoticeService.java
Labels: 디벨롭, 기능구현

#181 [Feature-0514](#179) - 메일 - 메일 등록, 받은 메일 수신자 읽음 여부 추가 수정
  src/main/java/com/devsplan/ketchup/mail/controller/MailController.java
  src/main/java/com/devsplan/ketchup/mail/dto/ReceiverDTO.java
  src/main/java/com/devsplan/ketchup/mail/service/MailService.java
  src/main/java/com/devsplan/ketchup/rsc/service/RscService.java
Labels: 디벨롭

#184 [Feature-0514] - {MemberController} 페이징없는 사원전체조회 추가 #183
  src/main/java/com/devsplan/ketchup/member/controller/MemberController.java
  src/main/java/com/devsplan/ketchup/member/dto/MemberDTO.java
  src/main/java/com/devsplan/ketchup/member/repository/MemberRepository.java
  src/main/java/com/devsplan/ketchup/member/service/MemberService.java
Labels: 기능구현

#185 [Feature-0515](#182) - 메일 - 메일 읽음 상태 변경
  src/main/java/com/devsplan/ketchup/mail/controller/MailController.java
  src/main/java/com/devsplan/ketchup/mail/entity/Receiver.java
  src/main/java/com/devsplan/ketchup/mail/repository/ReceiverRepository.java
  src/main/java/com/devsplan/ketchup/mail/service/MailService.java
Labels: 기능구현

#186 [Feature-0515](#180 #4 #46 #47) - board - 게시물 등록, 수정 파일업로드 controller, service 수정
  http/boardRestAPI.http
  src/main/java/com/devsplan/ketchup/board/controller/BoardController.java
  src/main/java/com/devsplan/ketchup/board/dto/BoardDTO.java
  src/main/java/com/devsplan/ketchup/board/dto/BoardFileDTO.java
  src/main/java/com/devsplan/ketchup/board/entity/Board.java
  src/main/java/com/devsplan/ketchup/board/entity/BoardFile.java
  src/main/java/com/devsplan/ketchup/board/repository/BoardRepository.java
  src/main/java/com/devsplan/ketchup/board/service/BoardService.java
  src/main/java/com/devsplan/ketchup/notice/controller/NoticeController.java
  src/main/java/com/devsplan/ketchup/notice/service/NoticeService.java
Labels: 디벨롭

#188 [Feature-0516](#187) - 카테고리별 문서 수
  http/approvalRestAPI.http
  src/main/java/com/devsplan/ketchup/approval/controller/ApprovalController.java
  src/main/java/com/devsplan/ketchup/approval/dto/ApprovalCountDTO.java
  src/main/java/com/devsplan/ketchup/approval/repository/ApprovalRepository.java
  src/main/java/com/devsplan/ketchup/approval/service/ApprovalService.java
  src/test/java/com/devsplan/ketchup/approval/ApprovalControllerTests.java
  src/test/java/com/devsplan/ketchup/approval/ApprovalServiceTests.java
Labels: 기능구현

#190 [Feature-0517 - {MemberController} 부서조회/직급조회 추가
  build.gradle
  http/memberRestAPI.http
  src/main/java/com/devsplan/ketchup/common/Authority.java
  src/main/java/com/devsplan/ketchup/member/controller/MemberController.java
  src/main/java/com/devsplan/ketchup/member/dto/MemberDTO.java
  src/main/java/com/devsplan/ketchup/member/repository/DepRepository.java
  src/main/java/com/devsplan/ketchup/member/repository/PositionRepository.java
  src/main/java/com/devsplan/ketchup/member/service/MemberService.java
Labels: 디벨롭, 기능구현

#191 [Feature-0517](#97) - 기안상신 - 기안상신할때 받아오는 List가 없을때 처리
  src/main/java/com/devsplan/ketchup/approval/controller/ApprovalController.java
  src/main/java/com/devsplan/ketchup/approval/service/ApprovalService.java
Labels: 디벨롭

#192 [Feature-0517](issue 번호) - 메일 - 메일 전송 코드 업데이트
  src/main/java/com/devsplan/ketchup/common/ResponseDTO.java
  src/main/java/com/devsplan/ketchup/mail/controller/MailController.java
  src/main/java/com/devsplan/ketchup/mail/service/MailService.java
Labels: 디벨롭

#194 [Feature-0518](#4 #46) - board - 게시물 등록, 수정 코드
  http/boardRestAPI.http
  src/main/java/com/devsplan/ketchup/board/controller/BoardController.java
  src/main/java/com/devsplan/ketchup/board/service/BoardService.java
  src/main/java/com/devsplan/ketchup/notice/service/NoticeService.java
  src/test/java/com/devsplan/ketchup/board/service/BoardServiceTests.java
Labels: 디벨롭

#196 [Feature-0519](#195) - reserve - 자원 예약 목록 조회 업데이트
  http/reserveRestAPI.http
  src/main/java/com/devsplan/ketchup/common/ScheduleBuilder.java
  src/main/java/com/devsplan/ketchup/reserve/controller/ReserveController.java
  src/main/java/com/devsplan/ketchup/reserve/dto/ReserveDTO.java
  src/main/java/com/devsplan/ketchup/reserve/entity/Reserve.java
  src/main/java/com/devsplan/ketchup/reserve/repository/ReserveRepository.java
  src/main/java/com/devsplan/ketchup/reserve/repository/ResourceRepository.java
  src/main/java/com/devsplan/ketchup/reserve/service/ReserveService.java
  src/main/java/com/devsplan/ketchup/rsc/dto/ResourceDTO.java
  src/main/java/com/devsplan/ketchup/rsc/entity/Resource.java
  src/test/java/com/devsplan/ketchup/mail/MailServiceTests.java
  src/test/java/com/devsplan/ketchup/reserve/ReserveControllerTests.java
  src/test/java/com/devsplan/ketchup/reserve/ReserveRepositoryTests.java
  src/test/java/com/devsplan/ketchup/reserve/ReserveServiceTests.java
Labels: 디벨롭, 에러, 기능구현

#198 [Feature-0520](#197) - 메일 - 메일 작성 코드 업데이트
  src/main/java/com/devsplan/ketchup/mail/controller/MailController.java
  src/main/java/com/devsplan/ketchup/mail/dto/MailDTO.java
  src/main/java/com/devsplan/ketchup/mail/entity/Mail.java
  src/main/java/com/devsplan/ketchup/mail/repository/MailFileRepository.java
  src/main/java/com/devsplan/ketchup/mail/service/MailService.java
Labels: 디벨롭, 에러

#200 [Feature-0520] - {MemberController, MemberService} 사원정보 수정 #199
  http/memberRestAPI.http
  src/main/java/com/devsplan/ketchup/member/controller/MemberController.java
  src/main/java/com/devsplan/ketchup/member/dto/MemberDTO.java
  src/main/java/com/devsplan/ketchup/member/entity/Member.java
  src/main/java/com/devsplan/ketchup/member/service/MemberService.java
  src/main/resources/application.yml
Labels: 기능구현

#201 [Feature-0520](#16 #22 #76) - board - 게시물 목록조회(페이징)
  src/main/java/com/devsplan/ketchup/board/controller/BoardController.java
  src/main/java/com/devsplan/ketchup/board/repository/BoardRepository.java
  src/main/java/com/devsplan/ketchup/board/service/BoardService.java
  src/main/java/com/devsplan/ketchup/notice/controller/NoticeController.java
Labels: 디벨롭

#202 [Feature-0521](#175) - JacksonConfig - 자원 예약 수정 중 Json parse error 해결
  http/mailRestAPI.http
  http/memberRestAPI.http
  http/reserveRestAPI.http
  http/rscRestAPI.http
  src/main/java/com/devsplan/ketchup/auth/config/WebSecurityConfig.java
  src/main/java/com/devsplan/ketchup/auth/handler/CustomAuthSuccessHandler.java
  src/main/java/com/devsplan/ketchup/config/JacksonConfig.java
  src/main/java/com/devsplan/ketchup/config/WebConfig.java
  src/main/java/com/devsplan/ketchup/reserve/controller/ReserveController.java
  src/main/java/com/devsplan/ketchup/reserve/dto/ReserveDTO.java
  src/main/java/com/devsplan/ketchup/reserve/service/ReserveService.java
  src/main/resources/application.yml
  src/test/java/com/devsplan/ketchup/reserve/ReserveServiceTests.java
Labels: 디벨롭

#203 [Feature-0521](issue 번호) - 자원 - 자원 조회 등록 코드 수정
  http/mailRestAPI.http
  http/rscRestAPI.http
  src/main/java/com/devsplan/ketchup/rsc/controller/RscController.java
  src/main/java/com/devsplan/ketchup/rsc/entity/Resource.java
  src/main/java/com/devsplan/ketchup/rsc/service/RscService.java
Labels: 디벨롭

#204 [Feature-0521](#3) - board - 게시물 상세조회
  src/main/java/com/devsplan/ketchup/board/controller/BoardController.java
  src/main/java/com/devsplan/ketchup/board/service/BoardService.java
  src/main/resources/application.yml
Labels: 디벨롭

#207 [Feature-0521] - {MemberController} 직급 삭제 추가
  http/memberRestAPI.http
  src/main/java/com/devsplan/ketchup/member/controller/AuthController.java
  src/main/java/com/devsplan/ketchup/member/controller/MemberController.java
  src/main/java/com/devsplan/ketchup/member/dto/PositionDTO.java
  src/main/java/com/devsplan/ketchup/member/entity/Position.java
  src/main/java/com/devsplan/ketchup/member/repository/PositionRepository.java
  src/main/java/com/devsplan/ketchup/member/service/MemberService.java
Labels: 기능구현

#210 [Feature-0522](#209) - boardService - 게시물 상세조회 이전, 다음글 이동
  src/main/java/com/devsplan/ketchup/board/controller/BoardController.java
  src/main/java/com/devsplan/ketchup/board/repository/BoardRepository.java
  src/main/java/com/devsplan/ketchup/board/service/BoardService.java
  src/main/java/com/devsplan/ketchup/notice/controller/NoticeController.java
  src/main/java/com/devsplan/ketchup/notice/dto/NoticeFileDTO.java
  src/main/java/com/devsplan/ketchup/notice/entity/NoticeFile.java
  src/main/java/com/devsplan/ketchup/notice/service/NoticeService.java
Labels: 디벨롭, 기능구현

#212 [Feature-0522](issue 번호) - 기능명 - 자원 수정, 조회 권한 수정
  src/main/java/com/devsplan/ketchup/rsc/controller/RscController.java
  src/main/java/com/devsplan/ketchup/rsc/service/RscService.java
Labels: 디벨롭

#213 [Feature-0522](#78) - notice- 공지 상세조회(이전, 다음글 이동), 공지 상세조회(파일 삭제)
  src/main/java/com/devsplan/ketchup/board/controller/BoardController.java
  src/main/java/com/devsplan/ketchup/board/entity/BoardFile.java
  src/main/java/com/devsplan/ketchup/board/service/BoardService.java
  src/main/java/com/devsplan/ketchup/notice/controller/NoticeController.java
  src/main/java/com/devsplan/ketchup/notice/repository/NoticeRepository.java
  src/main/java/com/devsplan/ketchup/notice/service/NoticeService.java
Labels: 디벨롭

#214 [Feature-0523](#59 #171) - notice - 공지 목록조회 수정
  src/main/java/com/devsplan/ketchup/notice/controller/NoticeController.java
  src/main/java/com/devsplan/ketchup/notice/service/NoticeService.java
Labels: 디벨롭

#217 [Feature-0523] - {MemberController} 직급 수정
  http/memberRestAPI.http
  src/main/java/com/devsplan/ketchup/auth/model/DetailsMember.java
  src/main/java/com/devsplan/ketchup/member/controller/MemberController.java
  src/main/java/com/devsplan/ketchup/member/service/MemberService.java
  src/main/resources/application.yml
Labels: 디벨롭, 기능구현

#219 [Feature-0524](issue 번호) - Resources - 자원 페이징 추가
  http/rscRestAPI.http
  src/main/java/com/devsplan/ketchup/rsc/controller/RscController.java
  src/main/java/com/devsplan/ketchup/rsc/repository/RscRepository.java
  src/main/java/com/devsplan/ketchup/rsc/service/RscService.java
Labels: 디벨롭

#220 [Feature-0524](#218) - comment- 게시물 댓글 dto, entity 생성
  src/main/java/com/devsplan/ketchup/board/controller/BoardController.java
  src/main/java/com/devsplan/ketchup/board/dto/BoardDTO.java
  src/main/java/com/devsplan/ketchup/board/entity/Board.java
  src/main/java/com/devsplan/ketchup/board/service/BoardService.java
  src/main/java/com/devsplan/ketchup/comment/controller/CommentController.java
  src/main/java/com/devsplan/ketchup/comment/dto/CommentDTO.java
  src/main/java/com/devsplan/ketchup/comment/entity/Comment.java
  src/main/java/com/devsplan/ketchup/comment/repository/CommentRepository.java
  src/main/java/com/devsplan/ketchup/comment/service/CommentService.java
  src/main/java/com/devsplan/ketchup/notice/service/NoticeService.java
  src/main/resources/application.yml
Labels: 기능구현

#223 [Feature-MMDD](#221) - Schedule - 일정 엔티티 PK auto increment 설정
  http/reserveRestAPI.http
  src/main/java/com/devsplan/ketchup/schedule/entity/Schedule.java
  src/test/java/com/devsplan/ketchup/reserve/ReserveControllerTests.java
Labels: 디벨롭

#226 [Feature-0524] - {Dep,DepDTO} 부서등록, 조회쿼리메소드 수정 #224
  http/memberRestAPI.http
  src/main/java/com/devsplan/ketchup/member/controller/MemberController.java
  src/main/java/com/devsplan/ketchup/member/dto/DepDTO.java
  src/main/java/com/devsplan/ketchup/member/entity/Dep.java
  src/main/java/com/devsplan/ketchup/member/repository/DepRepository.java
  src/main/java/com/devsplan/ketchup/member/service/MemberService.java
  src/test/java/com/devsplan/ketchup/member/MemberTest.java
Labels: 디벨롭

#230 [Feature-MMDD](#229) - Reserve - 자원예약 엔티티 수정
  src/main/java/com/devsplan/ketchup/reserve/controller/ReserveController.java
  src/main/java/com/devsplan/ketchup/reserve/dto/ReserveDTO.java
  src/main/java/com/devsplan/ketchup/reserve/entity/Reserve.java
  src/main/java/com/devsplan/ketchup/reserve/service/ReserveService.java
  src/main/resources/application.yml
  src/test/java/com/devsplan/ketchup/reserve/ReserveServiceTests.java
Labels: 디벨롭

#232 [Feature-0524] - {MemberController} 부서 수정, 부서삭제
  http/memberRestAPI.http
  src/main/java/com/devsplan/ketchup/member/controller/MemberController.java
  src/main/java/com/devsplan/ketchup/member/service/MemberService.java
  src/main/resources/application.yml
Labels: 기능구현

#234 [Feature-0525](#222 #225 #227 #228) - comment - 댓글 등록, 조회, 특정댓글조회, 수정, 삭제
  http/commentRestAPI.http
  src/main/java/com/devsplan/ketchup/comment/controller/CommentController.java
  src/main/java/com/devsplan/ketchup/comment/dto/CommentDTO.java
  src/main/java/com/devsplan/ketchup/comment/entity/Comment.java
  src/main/java/com/devsplan/ketchup/comment/repository/CommentRepository.java
  src/main/java/com/devsplan/ketchup/comment/service/CommentService.java
  src/main/java/com/devsplan/ketchup/config/SchedulerConfig.java
Labels: 기능구현

#236 [Feature-0524] - {MemberController} 부서 수정, 부서삭제
  http/memberRestAPI.http
  src/main/java/com/devsplan/ketchup/member/controller/MemberController.java
  src/main/java/com/devsplan/ketchup/member/service/MemberService.java
Labels: 기능구현

#237 [Feature-0527](#86) - Mail - 메일 페이징 추가
  http/mailRestAPI.http
  src/main/java/com/devsplan/ketchup/mail/controller/MailController.java
  src/main/java/com/devsplan/ketchup/mail/dto/MailDTO.java
  src/main/java/com/devsplan/ketchup/mail/dto/MailFileDTO.java
  src/main/java/com/devsplan/ketchup/mail/dto/ReceiverDTO.java
  src/main/java/com/devsplan/ketchup/mail/entity/Mail.java
  src/main/java/com/devsplan/ketchup/mail/entity/MailFile.java
  src/main/java/com/devsplan/ketchup/mail/entity/Receiver.java
  src/main/java/com/devsplan/ketchup/mail/repository/MailRepository.java
  src/main/java/com/devsplan/ketchup/mail/service/MailService.java
  src/main/java/com/devsplan/ketchup/rsc/controller/RscController.java
  src/main/java/com/devsplan/ketchup/rsc/dto/ResourceDTO.java
  src/main/java/com/devsplan/ketchup/rsc/repository/RscRepository.java
  src/main/java/com/devsplan/ketchup/rsc/service/RscService.java
Labels: 디벨롭

#239 [Feature-0422](#225) - comment - 조회 service코드수정
  http/commentRestAPI.http
  src/main/java/com/devsplan/ketchup/comment/controller/CommentController.java
  src/main/java/com/devsplan/ketchup/comment/dto/CommentDTO.java
  src/main/java/com/devsplan/ketchup/comment/entity/Comment.java
  src/main/java/com/devsplan/ketchup/comment/repository/CommentRepository.java
  src/main/java/com/devsplan/ketchup/comment/service/CommentService.java
  src/main/resources/application.yml
Labels: 디벨롭

#240 [Feature-0527](#238) - Mails - 받은 메일 개수 조회
  http/mailRestAPI.http
  src/main/java/com/devsplan/ketchup/mail/controller/MailController.java
  src/main/java/com/devsplan/ketchup/mail/repository/MailRepository.java
  src/main/java/com/devsplan/ketchup/mail/repository/ReceiverRepository.java
  src/main/java/com/devsplan/ketchup/mail/service/MailService.java
Labels: 기능구현

#242 [Feature-0527] - {MemberController} 최초로그인 비밀번호 수정/ 비밀번호 수정시 이메일API연동
  http/memberRestAPI.http
  src/main/java/com/devsplan/ketchup/auth/config/WebSecurityConfig.java
  src/main/java/com/devsplan/ketchup/auth/filter/JwtAuthorizationFilter.java
  src/main/java/com/devsplan/ketchup/member/controller/MemberController.java
  src/main/java/com/devsplan/ketchup/member/dto/MemberDTO.java
  src/main/java/com/devsplan/ketchup/member/entity/Member.java
  src/main/java/com/devsplan/ketchup/member/service/MemberService.java
  src/main/java/com/devsplan/ketchup/util/TokenUtils.java
  src/test/java/com/devsplan/ketchup/board/service/BoardServiceTests.java
  src/test/java/com/devsplan/ketchup/notice/service/NoticeServiceTests.java
  src/test/java/com/devsplan/ketchup/rsc/RscServiceTests.java
Labels: 디벨롭, 기능구현

#244 [Feature-MMDD](issue 번호) - 기능명 - 자원 상태 변경 또는 삭제 시 메일 내용 수정
  src/main/java/com/devsplan/ketchup/mail/repository/MailRepository.java
  src/main/java/com/devsplan/ketchup/mail/service/MailService.java
  src/main/java/com/devsplan/ketchup/rsc/service/RscService.java
Labels: 디벨롭

#245 [Feature-0528](#220) - board -댓글 dto, entity 수정
  src/main/java/com/devsplan/ketchup/comment/dto/CommentDTO.java
  src/main/java/com/devsplan/ketchup/comment/entity/Comment.java
  src/main/java/com/devsplan/ketchup/comment/service/CommentService.java
Labels: 디벨롭

#248 [Feature-0529] - {Dep,DepDTO,MemberController} 부서별 팀장추가
  http/memberRestAPI.http
  src/main/java/com/devsplan/ketchup/member/controller/MemberController.java
  src/main/java/com/devsplan/ketchup/member/dto/DepDTO.java
  src/main/java/com/devsplan/ketchup/member/entity/Dep.java
  src/main/java/com/devsplan/ketchup/member/repository/DepRepository.java
  src/main/java/com/devsplan/ketchup/member/service/MemberService.java
  src/main/java/com/devsplan/ketchup/rsc/controller/RscController.java
  src/main/resources/application.yml
Labels: 디벨롭

#249 [Feature-0529] Mail/Resource - 자원 권한 부서 코드에서 이름으로 수정, 주석 제거
  src/main/java/com/devsplan/ketchup/mail/repository/MailRepository.java
  src/main/java/com/devsplan/ketchup/mail/repository/ReceiverRepository.java
  src/main/java/com/devsplan/ketchup/mail/service/MailService.java
  src/main/java/com/devsplan/ketchup/rsc/controller/RscController.java
  src/main/java/com/devsplan/ketchup/rsc/repository/RscRepository.java
  src/main/java/com/devsplan/ketchup/rsc/service/RscService.java
Labels: 디벨롭

#250 [Feature-0530](#246) - Schedule - 일정 서비스에서 참여인원 수정시 기존 참여인원 삭제 후 새로운 참여인원 등록
  http/scheduleRestAPI.http
  src/main/java/com/devsplan/ketchup/schedule/controller/ScheduleController.java
  src/main/java/com/devsplan/ketchup/schedule/service/ScheduleService.java
  src/main/resources/application.yml
Labels: 디벨롭
