Repository devs-plan/Ketchup_Back-end, pull requests merged in 2024-04, with the labels that each got.

#8 0422 4시 pde
  src/main/java/com/devsplan/ketchup/mail/controller/MailController.java
  src/main/java/com/devsplan/ketchup/mail/dto/MailDTO.java
  src/main/java/com/devsplan/ketchup/mail/dto/MailFileDTO.java
  src/main/java/com/devsplan/ketchup/mail/dto/ReceiverDTO.java
  src/main/java/com/devsplan/ketchup/mail/entity/Mail.java
  src/main/java/com/devsplan/ketchup/mail/entity/MailFile.java
  src/main/java/com/devsplan/ketchup/mail/entity/Receiver.java
  src/main/java/com/devsplan/ketchup/mail/repository/MailRepository.java
  src/main/java/com/devsplan/ketchup/mail/service/MailService.java
  src/main/java/com/devsplan/ketchup/rsc/controller/RscController.java
  src/main/java/com/devsplan/ketchup/rsc/dto/rscDTO.java
  src/main/java/com/devsplan/ketchup/rsc/entity/Rsc.java
  src/main/java/com/devsplan/ketchup/rsc/repository/RscRepository.java
  src/main/java/com/devsplan/ketchup/rsc/service/RscService.java
Labels: 기능구현

#15 [Feature-0422](#3) - board - test코드 생성
  src/main/java/com/devsplan/ketchup/board/controller/BoardController.java
  src/main/java/com/devsplan/ketchup/board/entity/BoardFile.java
  src/main/java/com/devsplan/ketchup/mail/entity/Receiver.java
  src/main/java/com/devsplan/ketchup/util/FileUtils.java
  src/test/java/com/devsplan/ketchup/board/BoardRestTests.java
Labels: 기능구현

#20 [Feature-0423](#3) - schedule - 일정 http crud 테스트 완료
  http/scheduleRestAPI.http
  src/main/java/com/devsplan/ketchup/schedule/controller/ScheduleController.java
Labels: 기능구현

#22 [Feature-0422](#16) - board - 게시물 목록조회 test코드 작성
  src/main/java/com/devsplan/ketchup/board/controller/BoardController.java
  src/main/java/com/devsplan/ketchup/board/dto/BoardDTO.java
  src/main/java/com/devsplan/ketchup/board/dto/BoardFileDTO.java
  src/main/java/com/devsplan/ketchup/board/entity/Board.java
  src/main/java/com/devsplan/ketchup/board/entity/BoardAndMember.java
  src/main/java/com/devsplan/ketchup/board/entity/BoardFile.java
  src/main/java/com/devsplan/ketchup/board/service/BoardService.java
  src/main/java/com/devsplan/ketchup/member/DepartmentBoard.java
  src/main/java/com/devsplan/ketchup/member/DepartmentDTO.java
  src/main/java/com/devsplan/ketchup/member/Member.java
  src/main/java/com/devsplan/ketchup/member/MemberDTO.java
  src/test/java/com/devsplan/ketchup/Notice/NoticeRestTests.java
  src/test/java/com/devsplan/ketchup/board/BoardRestTests.java
Labels: 기능구현

#24 [Feature-0424](#19) - Approval - 기안등록
  src/main/java/com/devsplan/ketchup/approval/controller/ApprovalController.java
  src/main/java/com/devsplan/ketchup/approval/dto/AppLineDTO.java
  src/main/java/com/devsplan/ketchup/approval/dto/ApprovalDTO.java
  src/main/java/com/devsplan/ketchup/approval/dto/FormDTO.java
  src/main/java/com/devsplan/ketchup/approval/dto/RefLineDTO.java
  src/main/java/com/devsplan/ketchup/approval/entity/AppLine.java
  src/main/java/com/devsplan/ketchup/approval/entity/Approval.java
  src/main/java/com/devsplan/ketchup/approval/entity/Form.java
  src/main/java/com/devsplan/ketchup/approval/entity/RefLine.java
  src/main/java/com/devsplan/ketchup/approval/repository/AppLineRepository.java
  src/main/java/com/devsplan/ketchup/approval/repository/ApprovalRepository.java
  src/main/java/com/devsplan/ketchup/approval/repository/RefLineRepository.java
  src/main/java/com/devsplan/ketchup/approval/service/ApprovalService.java
  src/test/java/com/devsplan/ketchup/approval/ApprovalRestTests.java
Labels: 기능구현

#26 [Feature-0424](#25) - member - DTO,ENTITY 등록
  http/memberRestAPI.http
  src/main/java/com/devsplan/ketchup/auth/config/WebConfig.java
  src/main/java/com/devsplan/ketchup/auth/config/WebSecurityConfig.java
  src/main/java/com/devsplan/ketchup/auth/filter/CustomAuthenticationFilter.java
  src/main/java/com/devsplan/ketchup/auth/filter/HeaderFilter.java
  src/main/java/com/devsplan/ketchup/auth/filter/JwtAuthorizationFilter.java
  src/main/java/com/devsplan/ketchup/auth/handler/CustomAuthFailureHandler.java
  src/main/java/com/devsplan/ketchup/auth/handler/CustomAuthSuccessHandler.java
  src/main/java/com/devsplan/ketchup/auth/handler/CustomAuthenticationProvider.java
  src/main/java/com/devsplan/ketchup/auth/interceptor/JwtTokenInterceptor.java
  src/main/java/com/devsplan/ketchup/common/AuthConstants.java
  src/main/java/com/devsplan/ketchup/member/controller/AuthController.java
  src/main/java/com/devsplan/ketchup/member/controller/MemberController.java
  src/main/java/com/devsplan/ketchup/member/dto/AuthorityDTO.java
  src/main/java/com/devsplan/ketchup/member/dto/DepDTO.java
  src/main/java/com/devsplan/ketchup/member/dto/MemberDTO.java
  src/main/java/com/devsplan/ketchup/member/dto/PositionDTO.java
  src/main/java/com/devsplan/ketchup/member/dto/TokenDTO.java
  src/main/java/com/devsplan/ketchup/member/entity/Authority.java
  src/main/java/com/devsplan/ketchup/member/entity/Dep.java
  src/main/java/com/devsplan/ketchup/member/entity/Member.java
  src/main/java/com/devsplan/ketchup/member/entity/Position.java
  src/main/java/com/devsplan/ketchup/member/repository/MemberRepository.java
  src/main/java/com/devsplan/ketchup/member/service/MemberService.java
Labels: 디벨롭

#28 [Feature-0424](#25) - member - ENTITY 수정
  src/main/java/com/devsplan/ketchup/auth/model/DetailsUser.java
  src/main/java/com/devsplan/ketchup/auth/model/service/DetailsService.java
  src/main/java/com/devsplan/ketchup/member/entity/Member.java
  src/main/java/com/devsplan/ketchup/member/service/MemberService.java
Labels: 디벨롭

#29 [Feature-0424] - board - board DTO,Entity 수정
  http/memberRestAPI.http
  src/main/java/com/devsplan/ketchup/board/controller/BoardController.java
  src/main/java/com/devsplan/ketchup/board/dto/BoardDTO.java
  src/main/java/com/devsplan/ketchup/board/dto/BoardFileDTO.java
  src/main/java/com/devsplan/ketchup/board/entity/Board.java
  src/main/java/com/devsplan/ketchup/board/entity/BoardAndMember.java
  src/main/java/com/devsplan/ketchup/board/entity/BoardFile.java
  src/main/java/com/devsplan/ketchup/board/service/BoardService.java
  src/main/java/com/devsplan/ketchup/member/DepartmentBoard.java
  src/main/java/com/devsplan/ketchup/member/DepartmentDTO.java
  src/main/java/com/devsplan/ketchup/member/Member.java
  src/main/java/com/devsplan/ketchup/member/MemberDTO.java
  src/main/resources/application.yml
  src/test/java/com/devsplan/ketchup/board/BoardRestTests.java
  upload-dir/testFile.txt
Labels: 디벨롭

#33 [Feature-0424](#31 #32) - 메일 - 메일 등록, 조회 테스트
  http/mailRestAPI.http
  src/main/java/com/devsplan/ketchup/mail/controller/MailController.java
  src/main/java/com/devsplan/ketchup/mail/dto/MailDTO.java
  src/main/java/com/devsplan/ketchup/mail/dto/MailFileDTO.java
  src/main/java/com/devsplan/ketchup/mail/dto/ReceiverDTO.java
  src/main/java/com/devsplan/ketchup/mail/entity/Mail.java
  src/main/java/com/devsplan/ketchup/mail/entity/MailFile.java
  src/main/java/com/devsplan/ketchup/mail/entity/Receiver.java
  src/main/java/com/devsplan/ketchup/mail/repository/MailRepository.java
  src/main/java/com/devsplan/ketchup/mail/service/MailService.java
  src/test/java/com/devsplan/ketchup/mail/MailRestTests.java
Labels: 기능구현

#36 [Feature-0424](#35) - schedule - 부서별 일정 상세 조회 테스트
  src/main/java/com/devsplan/ketchup/schedule/repository/ScheduleRepository.java
  src/main/java/com/devsplan/ketchup/schedule/service/ScheduleService.java
  src/test/java/com/devsplan/ketchup/schedule/ScheduleRestTests.java
Labels: 기능구현

#39 [Feature-0425](#4, #38) - board - 게시물 등록 test코드, 게시물 목록 페이징 처리 추가
  src/main/java/com/devsplan/ketchup/board/dto/BoardFileDTO.java
  src/main/java/com/devsplan/ketchup/board/entity/Board.java
  src/main/java/com/devsplan/ketchup/board/entity/BoardFile.java
  src/main/java/com/devsplan/ketchup/board/repository/BoardRepository.java
  src/main/java/com/devsplan/ketchup/board/service/BoardService.java
  src/main/resources/application.yml
  src/test/java/com/devsplan/ketchup/board/BoardRestTests.java
  upload-dir/testFile.txt
Labels: 디벨롭, 기능구현

#40 [Feature-0425](#31 #32) - 메일 - 메일 수신자 등록, 발신 메일, 수신 메일 조회 테스트
  src/main/java/com/devsplan/ketchup/mail/dto/MailDTO.java
  src/main/java/com/devsplan/ketchup/mail/dto/ReceiverDTO.java
  src/main/java/com/devsplan/ketchup/mail/entity/Mail.java
  src/main/java/com/devsplan/ketchup/mail/entity/MailFile.java
  src/main/java/com/devsplan/ketchup/mail/entity/Receiver.java
  src/main/java/com/devsplan/ketchup/mail/repository/MailRepository.java
  src/main/java/com/devsplan/ketchup/mail/repository/ReceiverRepository.java
  src/main/java/com/devsplan/ketchup/mail/service/MailService.java
  src/test/java/com/devsplan/ketchup/mail/MailRestTests.java
Labels: 디벨롭, 기능구현

#42 [Feature-0425](#41) - MemberRestTest 사원,부서,직급 등록테스트 추가
  src/main/java/com/devsplan/ketchup/auth/config/WebConfig.java
  src/main/java/com/devsplan/ketchup/auth/config/WebSecurityConfig.java
  src/main/java/com/devsplan/ketchup/auth/filter/CustomAuthenticationFilter.java
  src/main/java/com/devsplan/ketchup/auth/filter/HeaderFilter.java
  src/main/java/com/devsplan/ketchup/auth/filter/JwtAuthorizationFilter.java
  src/main/java/com/devsplan/ketchup/auth/handler/CustomAuthSuccessHandler.java
  src/main/java/com/devsplan/ketchup/auth/handler/CustomAuthenticationProvider.java
  src/main/java/com/devsplan/ketchup/auth/interceptor/JwtTokenInterceptor.java
  src/main/java/com/devsplan/ketchup/auth/model/DetailsMember.java
  src/main/java/com/devsplan/ketchup/auth/model/dto/LoginDTO.java
  src/main/java/com/devsplan/ketchup/auth/model/service/DetailsService.java
  src/main/java/com/devsplan/ketchup/common/Authority.java
  src/main/java/com/devsplan/ketchup/common/utils/ConvertUtil.java
  src/main/java/com/devsplan/ketchup/common/utils/TokenUtils.java
  src/main/java/com/devsplan/ketchup/member/controller/AuthController.java
  src/main/java/com/devsplan/ketchup/member/controller/MemberController.java
  src/main/java/com/devsplan/ketchup/member/dto/AuthorityDTO.java
  src/main/java/com/devsplan/ketchup/member/dto/DepDTO.java
  src/main/java/com/devsplan/ketchup/member/dto/MemberDTO.java
  src/main/java/com/devsplan/ketchup/member/dto/PositionDTO.java
  src/main/java/com/devsplan/ketchup/member/entity/Authority.java
  src/main/java/com/devsplan/ketchup/member/entity/Dep.java
  src/main/java/com/devsplan/ketchup/member/entity/Member.java
  src/main/java/com/devsplan/ketchup/member/entity/Position.java
  src/main/java/com/devsplan/ketchup/member/repository/DepRepository.java
  src/main/java/com/devsplan/ketchup/member/repository/MemberRepository.java
  src/main/java/com/devsplan/ketchup/member/repository/PositionRepository.java
  src/main/java/com/devsplan/ketchup/member/service/MemberService.java
  src/test/java/com/devsplan/ketchup/member/MemberRestTest.java
Labels: 기능구현

#48 [Feature-0422](#23 #46 #47 ) - board - 게시물 목록 검색조회, 게시물 수정, 게시물 삭제
  src/main/java/com/devsplan/ketchup/board/controller/BoardController.java
  src/main/java/com/devsplan/ketchup/board/dto/BoardDTO.java
  src/main/java/com/devsplan/ketchup/board/dto/BoardFileDTO.java
  src/main/java/com/devsplan/ketchup/board/entity/Board.java
  src/main/java/com/devsplan/ketchup/board/entity/BoardFile.java
  src/main/java/com/devsplan/ketchup/board/repository/BoardRepository.java
  src/main/java/com/devsplan/ketchup/board/service/BoardService.java
  src/main/java/com/devsplan/ketchup/config/WebConfig.java
  src/test/java/com/devsplan/ketchup/board/BoardRestTests.java
  src/test/java/com/devsplan/ketchup/board/service/BoardServiceTests.java
  upload-dir/testFile.txt
Labels: 기능구현

#49 [Feature-0426](#43 #45) - 메일 - 발송 취소, 메일 삭제
  src/main/java/com/devsplan/ketchup/mail/dto/ReceiverDTO.java
  src/main/java/com/devsplan/ketchup/mail/repository/MailRepository.java
  src/main/java/com/devsplan/ketchup/mail/repository/ReceiverRepository.java
  src/main/java/com/devsplan/ketchup/mail/service/MailService.java
  src/test/java/com/devsplan/ketchup/mail/MailRestTests.java
Labels: 기능구현

#51 [Feature-0426](#43 #45) - 메일 - 발송 취소, 메일 삭제
  src/main/java/com/devsplan/ketchup/mail/dto/MailDTO.java
  src/main/java/com/devsplan/ketchup/mail/dto/ReceiverDTO.java
  src/main/java/com/devsplan/ketchup/mail/entity/Mail.java
  src/main/java/com/devsplan/ketchup/mail/entity/Receiver.java
  src/main/java/com/devsplan/ketchup/mail/repository/MailRepository.java
  src/main/java/com/devsplan/ketchup/mail/repository/ReceiverRepository.java
  src/main/java/com/devsplan/ketchup/mail/service/MailService.java
  src/test/java/com/devsplan/ketchup/mail/MailRestTests.java
Labels: 기능구현

#52 [Feature-0426] - 메일 - 파일 수정
  src/main/java/com/devsplan/ketchup/mail/repository/ReceiverRepository.java
  src/main/java/com/devsplan/ketchup/mail/service/MailService.java
Labels: 에러

#53 [Feature-0426](#30) - board - 부서별 자료실 게시물 등록 첨부파일 등록 test코드 생성
  src/main/java/com/devsplan/ketchup/board/dto/BoardDTO.java
  src/main/java/com/devsplan/ketchup/board/dto/BoardFileDTO.java
  src/main/java/com/devsplan/ketchup/board/entity/Board.java
  src/main/java/com/devsplan/ketchup/board/entity/BoardFile.java
  src/main/java/com/devsplan/ketchup/board/service/BoardService.java
  src/main/java/com/devsplan/ketchup/mail/repository/MailRepository.java
  src/main/java/com/devsplan/ketchup/mail/repository/ReceiverRepository.java
  src/main/java/com/devsplan/ketchup/notice/controller/NoticeController.java
  src/main/java/com/devsplan/ketchup/util/FileUtils.java
  src/main/resources/application.yml
  src/test/java/com/devsplan/ketchup/board/service/BoardServiceTests.java
  src/test/java/com/devsplan/ketchup/mail/MailRestTests.java
  upload-dir/testFile.txt
Labels: 기능구현

#56 [Feature-0422](#46 #47 #54) - board - 부서별 자료실 게시물 등록,수정,삭제 test코드 생성 및 수정
  src/main/java/com/devsplan/ketchup/board/controller/BoardController.java
  src/main/java/com/devsplan/ketchup/board/dto/BoardDTO.java
  src/main/java/com/devsplan/ketchup/board/dto/BoardFileDTO.java
  src/main/java/com/devsplan/ketchup/board/entity/Board.java
  src/main/java/com/devsplan/ketchup/board/entity/BoardFile.java
  src/main/java/com/devsplan/ketchup/board/service/BoardService.java
  src/main/java/com/devsplan/ketchup/common/ResponseDTO.java
  src/main/java/com/devsplan/ketchup/util/FileUtils.java
  src/test/java/com/devsplan/ketchup/board/service/BoardServiceTests.java
Labels: 기능구현

#62 [Feature-0429](#61) - schedule - 부서별 일정 수정 테스트
  src/main/java/com/devsplan/ketchup/common/ScheduleBuilder.java
  src/main/java/com/devsplan/ketchup/schedule/entity/Schedule.java
  src/main/java/com/devsplan/ketchup/schedule/service/ScheduleService.java
  src/test/java/com/devsplan/ketchup/schedule/ScheduleRestTests.java
Labels: 기능구현

#64 [Feature-0429](#63) - 스프링시큐리티jwt 추가/로그인 추가
  build.gradle
  http/memberRestAPI.http
  src/main/java/com/devsplan/ketchup/auth/config/WebConfig.java
  src/main/java/com/devsplan/ketchup/auth/config/WebSecurityConfig.java
  src/main/java/com/devsplan/ketchup/auth/filter/CustomAuthenticationFilter.java
  src/main/java/com/devsplan/ketchup/auth/filter/JwtAuthorizationFilter.java
  src/main/java/com/devsplan/ketchup/auth/handler/CustomAuthFailureHandler.java
  src/main/java/com/devsplan/ketchup/auth/handler/CustomAuthSuccessHandler.java
  src/main/java/com/devsplan/ketchup/auth/handler/CustomAuthenticationProvider.java
  src/main/java/com/devsplan/ketchup/auth/interceptor/JwtTokenInterceptor.java
  src/main/java/com/devsplan/ketchup/auth/model/DetailsMember.java
  src/main/java/com/devsplan/ketchup/auth/model/dto/LoginDTO.java
  src/main/java/com/devsplan/ketchup/auth/model/service/DetailsService.java
  src/main/java/com/devsplan/ketchup/board/repository/BoardFileRepository.java
  src/main/java/com/devsplan/ketchup/board/repository/BoardRepository.java
  src/main/java/com/devsplan/ketchup/common/Authority.java
  src/main/java/com/devsplan/ketchup/common/utils/ConvertUtil.java
  src/main/java/com/devsplan/ketchup/common/utils/TokenUtils.java
  src/main/java/com/devsplan/ketchup/config/WebConfig.java
  src/main/java/com/devsplan/ketchup/member/controller/MemberController.java
  src/main/java/com/devsplan/ketchup/member/controller/TestController.java
  src/main/java/com/devsplan/ketchup/member/dto/DepDTO.java
  src/main/java/com/devsplan/ketchup/member/dto/MemberDTO.java
  src/main/java/com/devsplan/ketchup/member/dto/PositionDTO.java
  src/main/java/com/devsplan/ketchup/member/entity/Member.java
  src/main/java/com/devsplan/ketchup/member/entity/Position.java
  src/main/java/com/devsplan/ketchup/member/repository/DepRepository.java
  src/main/java/com/devsplan/ketchup/member/repository/MemberRepository.java
  src/main/java/com/devsplan/ketchup/member/repository/PositionRepository.java
  src/main/java/com/devsplan/ketchup/member/service/MemberService.java
  src/main/java/com/devsplan/ketchup/util/TokenUtils.java
  src/main/resources/application.yml
  src/test/java/com/devsplan/ketchup/member/MemberRestTest.java
Labels: 기능구현

#65 [Feature-0428](#44) - 전자결재 목록조회 - service
  http/approvalRestAPI.http
  src/main/java/com/devsplan/ketchup/approval/controller/ApprovalController.java
  src/main/java/com/devsplan/ketchup/approval/dto/ApprovalDTO.java
  src/main/java/com/devsplan/ketchup/approval/dto/ApprovalSelectDTO.java
  src/main/java/com/devsplan/ketchup/approval/entity/AppLine.java
  src/main/java/com/devsplan/ketchup/approval/entity/Approval.java
  src/main/java/com/devsplan/ketchup/approval/entity/ApprovalSelect.java
  src/main/java/com/devsplan/ketchup/approval/entity/Form.java
  src/main/java/com/devsplan/ketchup/approval/entity/RefLine.java
  src/main/java/com/devsplan/ketchup/approval/repository/AppLineRepository.java
  src/main/java/com/devsplan/ketchup/approval/repository/ApprovalSelectRepository.java
  src/main/java/com/devsplan/ketchup/approval/repository/RefLineRepository.java
  src/main/java/com/devsplan/ketchup/approval/service/ApprovalService.java
  src/main/java/com/devsplan/ketchup/board/service/BoardService.java
  src/test/java/com/devsplan/ketchup/approval/ApprovalControllerTests.java
  src/test/java/com/devsplan/ketchup/approval/ApprovalRestTests.java
Labels: 기능구현

#66 [Bug-0429](#63) - memberRestTest 오타 수정
  http/memberRestAPI.http
  src/main/java/com/devsplan/ketchup/board/service/BoardService.java
  src/main/java/com/devsplan/ketchup/member/controller/TestController.java
  src/main/resources/application.yml
  src/test/java/com/devsplan/ketchup/member/MemberRestTest.java
Labels: 에러

#71 [Feature-0429](#70) - schedule - 부서별 일정 삭제 테스트
  src/main/java/com/devsplan/ketchup/board/repository/BoardRepository.java
  src/main/java/com/devsplan/ketchup/common/utils/TokenUtils.java
  src/main/java/com/devsplan/ketchup/schedule/repository/ScheduleRepository.java
  src/main/java/com/devsplan/ketchup/schedule/service/ScheduleService.java
  src/test/java/com/devsplan/ketchup/schedule/ScheduleRestTests.java
Labels: 기능구현

#73 [Feature-0429] - {TestController} 로그인 이후 토큰의 클레임에서 부서정보 조회
  http/memberRestAPI.http
  src/main/java/com/devsplan/ketchup/auth/filter/JwtAuthorizationFilter.java
  src/main/java/com/devsplan/ketchup/member/controller/TestController.java
  src/main/java/com/devsplan/ketchup/member/entity/Dep.java
  src/main/java/com/devsplan/ketchup/util/TokenUtils.java
Labels: 디벨롭

#74 [Feature-0429] - 메일 - 메일 관련 기능 전체 수정
  http/mailRestAPI.http
  src/main/java/com/devsplan/ketchup/mail/dto/MailDTO.java
  src/main/java/com/devsplan/ketchup/mail/dto/ReceiverDTO.java
  src/main/java/com/devsplan/ketchup/mail/entity/Mail.java
  src/main/java/com/devsplan/ketchup/mail/entity/Receiver.java
  src/main/java/com/devsplan/ketchup/mail/repository/MailRepository.java
  src/main/java/com/devsplan/ketchup/mail/repository/ReceiverRepository.java
  src/main/java/com/devsplan/ketchup/mail/service/MailService.java
  src/test/java/com/devsplan/ketchup/mail/MailRestTests.java
  src/test/java/com/devsplan/ketchup/mail/service/MailRestTests.java
Labels: 디벨롭

#76 [Feature-0430](#55) - board - 게시물 등록, 수정, 삭제 시큐리티 연결, 목록조회, 상세조회test코드 생성
  http/boardRestAPI.http
  http/memberRestAPI.http
  src/main/java/com/devsplan/ketchup/board/controller/BoardController.java
  src/main/java/com/devsplan/ketchup/board/dto/BoardDTO.java
  src/main/java/com/devsplan/ketchup/board/entity/Board.java
  src/main/java/com/devsplan/ketchup/board/entity/BoardAndMember.java
  src/main/java/com/devsplan/ketchup/board/entity/BoardFile.java
  src/main/java/com/devsplan/ketchup/board/repository/BoardFileRepository.java
  src/main/java/com/devsplan/ketchup/board/repository/BoardRepository.java
  src/main/java/com/devsplan/ketchup/board/service/BoardService.java
  src/main/java/com/devsplan/ketchup/util/FileUtils.java
  src/main/resources/application.yml
  src/test/java/com/devsplan/ketchup/board/service/BoardServiceTests.java
Labels: 디벨롭, 기능구현

#77 [Feature-0430](#57) - notice- 공지사항 DTO, Entity 생성, service test코드 작성
  http/boardRestAPI.http
  src/main/java/com/devsplan/ketchup/board/controller/BoardController.java
  src/main/java/com/devsplan/ketchup/board/dto/BoardDTO.java
  src/main/java/com/devsplan/ketchup/board/service/BoardService.java
  src/main/java/com/devsplan/ketchup/notice/controller/NoticeController.java
  src/main/java/com/devsplan/ketchup/notice/dto/NoticeDTO.java
  src/main/java/com/devsplan/ketchup/notice/entity/Notice.java
  src/main/java/com/devsplan/ketchup/notice/repository/NoticeRepository.java
  src/main/java/com/devsplan/ketchup/notice/service/NoticeService.java
  src/test/java/com/devsplan/ketchup/Notice/NoticeRestTests.java
  src/test/java/com/devsplan/ketchup/board/service/BoardServiceTests.java
  src/test/java/com/devsplan/ketchup/notice/service/NoticeServiceTests.java
Labels: 기능구현

#78 [Feature-0430] - notice- 게시글 파일 class수정
  src/main/java/com/devsplan/ketchup/notice/dto/NoticeFileDTO.java
  src/main/java/com/devsplan/ketchup/notice/entity/NoticeFile.java
  src/main/java/com/devsplan/ketchup/notice/repository/NoticeFileRepository.java
Labels: 기능구현

#79 [Feature-0430](#58, #59) - notice- 공지사항 등록, 수정, 삭제, 목록조회, 상세조회 service test코드 작성
  http/boardRestAPI.http
  src/main/java/com/devsplan/ketchup/board/service/BoardService.java
  src/main/java/com/devsplan/ketchup/notice/dto/NoticeDTO.java
  src/main/java/com/devsplan/ketchup/notice/entity/Notice.java
  src/main/java/com/devsplan/ketchup/notice/entity/NoticeFile.java
  src/main/java/com/devsplan/ketchup/notice/repository/NoticeFileRepository.java
  src/main/java/com/devsplan/ketchup/notice/repository/NoticeRepository.java
  src/main/java/com/devsplan/ketchup/notice/service/NoticeService.java
  src/test/java/com/devsplan/ketchup/notice/service/NoticeServiceTests.java
Labels: 기능구현

#81 [Feature-0430](#68) - 전자결재 업데이트 - 전자결재 회수, 결재처리
  http/approvalRestAPI.http
  src/main/java/com/devsplan/ketchup/approval/controller/ApprovalController.java
  src/main/java/com/devsplan/ketchup/approval/dto/AppLineDTO.java
  src/main/java/com/devsplan/ketchup/approval/dto/AppUpdateDTO.java
  src/main/java/com/devsplan/ketchup/approval/dto/ApprovalDTO.java
  src/main/java/com/devsplan/ketchup/approval/dto/ApprovalSelectDTO.java
  src/main/java/com/devsplan/ketchup/approval/dto/RefLineDTO.java
  src/main/java/com/devsplan/ketchup/approval/entity/AppFile.java
  src/main/java/com/devsplan/ketchup/approval/entity/AppLine.java
  src/main/java/com/devsplan/ketchup/approval/entity/Approval.java
  src/main/java/com/devsplan/ketchup/approval/entity/ApprovalSelect.java
  src/main/java/com/devsplan/ketchup/approval/entity/Form.java
  src/main/java/com/devsplan/ketchup/approval/entity/RefLine.java
  src/main/java/com/devsplan/ketchup/approval/repository/AppLineRepository.java
  src/main/java/com/devsplan/ketchup/approval/repository/ApprovalSelectRepository.java
  src/main/java/com/devsplan/ketchup/approval/repository/RefLineRepository.java
  src/main/java/com/devsplan/ketchup/approval/service/ApprovalService.java
  src/test/java/com/devsplan/ketchup/approval/ApprovalControllerTests.java
  src/test/java/com/devsplan/ketchup/approval/ApprovalRestTests.java
Labels: 기능구현

#84 [Feature-0430] - ALL직급 삭제, 직급수정 추가
  http/memberRestAPI.http
  src/main/java/com/devsplan/ketchup/auth/handler/CustomAuthenticationProvider.java
  src/main/java/com/devsplan/ketchup/common/Authority.java
  src/main/java/com/devsplan/ketchup/member/controller/MemberController.java
  src/main/java/com/devsplan/ketchup/member/service/MemberService.java
  src/main/java/com/devsplan/ketchup/util/TokenUtils.java
  src/main/resources/static/uploadfiles/test9
  src/test/java/com/devsplan/ketchup/member/MemberRestTest.java
Labels: 디벨롭, 기능구현

#87 [Feature-0430](#85 #86) - 메일 - 메일 등록, 조회 테스트
  http/mailRestAPI.http
  src/main/java/com/devsplan/ketchup/mail/controller/MailController.java
  src/main/java/com/devsplan/ketchup/mail/dto/MailDTO.java
  src/main/java/com/devsplan/ketchup/mail/dto/ReceiverDTO.java
  src/main/java/com/devsplan/ketchup/mail/entity/Mail.java
  src/main/java/com/devsplan/ketchup/mail/entity/Receiver.java
  src/main/java/com/devsplan/ketchup/mail/repository/MailRepository.java
  src/main/java/com/devsplan/ketchup/mail/repository/ReceiverRepository.java
  src/main/java/com/devsplan/ketchup/mail/service/MailService.java
  src/test/java/com/devsplan/ketchup/mail/controller/MailControllerTests.java
  src/test/java/com/devsplan/ketchup/mail/service/MailRestTests.java
Labels: 디벨롭, 기능구현

#89 [Feature-0430](#88) - reserve - Reserve 예약 관련 패키지 작성 완료
  http/reserveRestAPI.http
  http/scheduleRestAPI.http
  src/main/java/com/devsplan/ketchup/config/WebConfig.java
  src/main/java/com/devsplan/ketchup/reserve/controller/ReserveController.java
  src/main/java/com/devsplan/ketchup/reserve/dto/ReserveDTO.java
  src/main/java/com/devsplan/ketchup/reserve/entity/Reserve.java
  src/main/java/com/devsplan/ketchup/reserve/repository/ReserveRepository.java
  src/main/java/com/devsplan/ketchup/reserve/service/ReserveService.java
  src/main/java/com/devsplan/ketchup/schedule/controller/ScheduleController.java
  src/test/java/com/devsplan/ketchup/schedule/ScheduleRestTests.java
Labels: 기능구현

#90 [Feature-0430](#60, #80) - board - 공지 등록, 수정, 삭제, 목록조회, 상세조회 controller test코드 작성
  http/boardRestAPI.http
  http/noticeRestAPI.http
  src/main/java/com/devsplan/ketchup/board/controller/BoardController.java
  src/main/java/com/devsplan/ketchup/board/service/BoardService.java
  src/main/java/com/devsplan/ketchup/notice/controller/NoticeController.java
  src/main/java/com/devsplan/ketchup/notice/dto/NoticeDTO.java
  src/main/java/com/devsplan/ketchup/notice/dto/NoticeFileDTO.java
  src/main/java/com/devsplan/ketchup/notice/repository/NoticeFileRepository.java
  src/main/java/com/devsplan/ketchup/notice/repository/NoticeRepository.java
  src/main/java/com/devsplan/ketchup/notice/service/NoticeService.java
  src/test/java/com/devsplan/ketchup/notice/controller/NoticeControllerTests.java
  src/test/java/com/devsplan/ketchup/notice/service/NoticeServiceTests.java
Labels: 디벨롭, 기능구현
